---
version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - enhancement
    groups:
      nuget:
        patterns:
          - "*"
    cooldown:
      default-days: 7
  - package-ecosystem: npm
    directory: "/Tools"
    directory: "/Web"
    schedule:
      interval: weekly
    labels:
      - enhancement
    groups:
      npm:
        patterns:
          - "*"
    cooldown:
      default-days: 7
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - enhancement
    groups:
      docker:
        patterns:
          - "*"
    cooldown:
      default-days: 7
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - enhancement
    groups:
      actions:
        patterns:
          - "*"
    cooldown:
      default-days: 7
