version: 1.0.{build}
image: Visual Studio 2017
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
before_build:
- nuget restore
configuration: Release
build_script:
- sh: msbuild "C:\projects\imgbot\ImgBot.sln" /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" || msbuild || dotnet build
