version: 1.0.{build}
image: Visual Studio 2017
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
before_build:
- nuget restore
configuration: Release
build_script:
- sh: msbuild "C:\projects\imgbot\ImgBot.sln" /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" || msbuild || dotnet build
- cmd: set PATH=C:\msys64\usr\bin;C:\msys64\mingw64\bin;%PATH%
- cmd: appveyor DownloadFile "https://raw.githubusercontent.com/swig/cccl/master/cccl"
- cmd: call "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" %PLATFORM%
- cmd: vcpkg update
- cmd: .\vcpkg install vcpkg-msbuild
- cmd: bash -cvx "if test -x \"$(which scoop)\"; then (scoop bucket add extras && scoop install extras/msbuild-structured-log-viewer); fi
- cmd: bash -cvx "msbuild \"C:\projects\imgbot\ImgBot.sln\" /verbosity:minimal /logger:\"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll\" || msbuild || dotnet build || dotnet msbuild || dotnet test || dotnet vstest ImgBot.sln || ls -R"
